name: Snyk
on: pull_request
jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_ACTION_ROLE }}
        with:
          command: test
          args: --severity-threshold=high
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_ACTION_ROLE }}
        with:
          command: code test
          args: --severity-threshold=high
